// -----------------------------------------------------------------------
//  <copyright file="ConfigurationSnapshotSpec.cs" company="Akka.NET Project">
//      Copyright (C) 2013-2023 .NET Foundation <https://github.com/akkadotnet/akka.net>
//  </copyright>
// -----------------------------------------------------------------------

using System.Data;
using Akka.Actor;
using Akka.Configuration;
using Akka.Hosting;
using Akka.Persistence.Hosting;
using Akka.Persistence.Journal;
using Akka.Persistence.Sql.Config;
using LinqToDB;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Xunit;

namespace Akka.Persistence.Sql.Hosting.Tests;

/// <summary>
/// Comprehensive snapshot tests to validate HOCON configuration generated by various WithSqlPersistence scenarios.
/// This is to detect configuration regressions between versions.
/// </summary>
public class ConfigurationSnapshotSpec
{
    private const string ConnectionString = "DataSource=:memory:";
    private const string TestProviderName = LinqToDB.ProviderName.SQLite;

    /// <summary>
    /// Test event adapter for testing purposes
    /// </summary>
    private class TestEventAdapter : IWriteEventAdapter
    {
        public string Manifest(object evt) => string.Empty;

        public object ToJournal(object evt)
        {
            if (evt is string str && str.StartsWith("tag:"))
            {
                return new Tagged(str, new[] { "test-tag" });
            }
            return evt;
        }
    }

    /// <summary>
    /// Another test event adapter
    /// </summary>
    private class AnotherEventAdapter : IReadEventAdapter
    {
        public IEventSequence FromJournal(object evt, string manifest) =>
            EventSequence.Single(evt);
    }

    private class TestEvent { }
    private class AnotherTestEvent { }

    private static async Task<Configuration.Config> BuildAndGetConfig(Action<AkkaConfigurationBuilder> configure)
    {
        var host = new HostBuilder()
            .ConfigureServices((context, services) =>
            {
                services.AddAkka("test-system", configure);
            })
            .Build();

        await host.StartAsync();
        try
        {
            var system = host.Services.GetRequiredService<ActorSystem>();
            return system.Settings.Config;
        }
        finally
        {
            await host.StopAsync();
            host.Dispose();
        }
    }

    [Fact]
    public async Task BasicConfiguration_NoAdapters()
    {
        // Act
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both);
        });

        // Assert - snapshot relevant HOCON sections
        var snapshot = new
        {
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString(),
            Snapshot = config.GetConfig("akka.persistence.snapshot-store.sql").ToString(),
            EventAdapters = config.GetConfig("akka.persistence.journal.sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.sql.event-adapter-bindings")?.ToString() ?? "null"
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(BasicConfiguration_NoAdapters)}");
    }

    [Fact]
    public async Task Configuration_WithWriteEventAdapter()
    {
        // Act
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("test-adapter",
                        new[] { typeof(TestEvent) }));
        });

        // Assert - snapshot relevant HOCON sections
        var snapshot = new
        {
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString(),
            Snapshot = config.GetConfig("akka.persistence.snapshot-store.sql").ToString(),
            EventAdapters = config.GetConfig("akka.persistence.journal.sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.sql.event-adapter-bindings")?.ToString() ?? "null"
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_WithWriteEventAdapter)}");
    }

    [Fact]
    public async Task Configuration_WithMultipleEventAdapters()
    {
        // Act
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("test-adapter",
                        new[] { typeof(TestEvent) })
                    .AddReadEventAdapter<AnotherEventAdapter>("another-adapter",
                        new[] { typeof(AnotherTestEvent) }));
        });

        // Assert - snapshot relevant HOCON sections
        var snapshot = new
        {
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString(),
            Snapshot = config.GetConfig("akka.persistence.snapshot-store.sql").ToString(),
            EventAdapters = config.GetConfig("akka.persistence.journal.sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.sql.event-adapter-bindings")?.ToString() ?? "null"
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_WithMultipleEventAdapters)}");
    }

    [Fact]
    public async Task Configuration_JournalOnly_WithAdapter()
    {
        // Act
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Journal,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("test-adapter",
                        new[] { typeof(TestEvent) }));
        });

        // Assert - snapshot relevant HOCON sections
        var snapshot = new
        {
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString(),
            SnapshotExists = config.HasPath("akka.persistence.snapshot-store.sql"),
            EventAdapters = config.GetConfig("akka.persistence.journal.sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.sql.event-adapter-bindings")?.ToString() ?? "null"
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_JournalOnly_WithAdapter)}");
    }

    // NOTE: This test uses a lower-level API (journalBuilder parameter) that was added in v1.5.51.1
    // Uncomment when running on v1.5.51.1 or later
    /*
    [Fact]
    public async Task Configuration_SqlJournalOptions_WithAdapter()
    {
        // Act
        var config = await BuildAndGetConfig(builder =>
        {
            var journalOpt = new SqlJournalOptions
            {
                ConnectionString = ConnectionString,
                ProviderName = TestProviderName,
                AutoInitialize = true
            };

            // Using the lower-level API
            builder.WithSqlPersistence(
                journalOptions: journalOpt,
                snapshotOptions: null,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("test-adapter",
                        new[] { typeof(TestEvent) }),
                snapshotBuilder: null);
        });

        // Assert - snapshot relevant HOCON sections
        var snapshot = new
        {
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString(),
            EventAdapters = config.GetConfig("akka.persistence.journal.sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.sql.event-adapter-bindings")?.ToString() ?? "null"
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_SqlJournalOptions_WithAdapter)}");
    }
    */

    [Fact]
    public async Task Configuration_CustomPluginId_WithAdapter()
    {
        // Act
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                pluginIdentifier: "custom-sql",
                isDefaultPlugin: false,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("test-adapter",
                        new[] { typeof(TestEvent) }));
        });

        // Assert - snapshot relevant HOCON sections
        var snapshot = new
        {
            Journal = config.GetConfig("akka.persistence.journal.custom-sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.custom-sql").ToString(),
            Snapshot = config.GetConfig("akka.persistence.snapshot-store.custom-sql").ToString(),
            EventAdapters = config.GetConfig("akka.persistence.journal.custom-sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.custom-sql.event-adapter-bindings")?.ToString() ?? "null"
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_CustomPluginId_WithAdapter)}");
    }

    [Fact]
    public async Task Configuration_TagTableMode_WithAdapter()
    {
        // Act - using TagTable mode (critical for query performance and the reported bug)
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                tagStorageMode: TagMode.TagTable,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("test-adapter",
                        new[] { typeof(TestEvent) }));
        });

        // Assert - verify tag-write-mode and tag-read-mode are set correctly
        var snapshot = new
        {
            JournalTagWriteMode = config.GetString("akka.persistence.journal.sql.tag-write-mode"),
            QueryTagReadMode = config.GetString("akka.persistence.query.journal.sql.tag-read-mode"),
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString(),
            EventAdapters = config.GetConfig("akka.persistence.journal.sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.sql.event-adapter-bindings")?.ToString() ?? "null"
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_TagTableMode_WithAdapter)}");
    }

    [Fact]
    public async Task Configuration_CsvTagMode_WithAdapter()
    {
        // Act - using CSV mode for tags
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                tagStorageMode: TagMode.Csv,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("test-adapter",
                        new[] { typeof(TestEvent) }));
        });

        // Assert
        var snapshot = new
        {
            JournalTagWriteMode = config.GetString("akka.persistence.journal.sql.tag-write-mode"),
            QueryTagReadMode = config.GetString("akka.persistence.query.journal.sql.tag-read-mode"),
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString()
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_CsvTagMode_WithAdapter)}");
    }

    [Fact]
    public async Task Configuration_WithQueryThrottling()
    {
        // Act - test max-concurrent-queries configuration
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                maxConcurrentQueries: 50);
        });

        // Assert - verify query throttling is configured
        var snapshot = new
        {
            MaxConcurrentQueries = config.GetInt("akka.persistence.query.journal.sql.max-concurrent-queries"),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString()
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_WithQueryThrottling)}");
    }

    [Fact]
    public async Task Configuration_WithIsolationLevels()
    {
        // Act - test read/write isolation level configuration
        var config = await BuildAndGetConfig(builder =>
        {
            var journalOpt = new SqlJournalOptions
            {
                ConnectionString = ConnectionString,
                ProviderName = TestProviderName,
                ReadIsolationLevel = IsolationLevel.ReadCommitted,
                WriteIsolationLevel = IsolationLevel.Serializable
            };

            builder.WithSqlPersistence(journalOptions: journalOpt);
        });

        // Assert
        var snapshot = new
        {
            JournalReadIsolation = config.GetString("akka.persistence.journal.sql.read-isolation-level"),
            JournalWriteIsolation = config.GetString("akka.persistence.journal.sql.write-isolation-level"),
            QueryReadIsolation = config.GetString("akka.persistence.query.journal.sql.read-isolation-level"),
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString()
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_WithIsolationLevels)}");
    }

    [Fact]
    public async Task Configuration_WithDeleteCompatibilityMode()
    {
        // Act
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                deleteCompatibilityMode: true);
        });

        // Assert
        var snapshot = new
        {
            DeleteCompatibilityMode = config.GetBoolean("akka.persistence.journal.sql.delete-compatibility-mode"),
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString()
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_WithDeleteCompatibilityMode)}");
    }

    [Fact]
    public async Task Configuration_WithWriterUuidColumn()
    {
        // Act
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                useWriterUuidColumn: true);
        });

        // Assert
        var snapshot = new
        {
            UseWriterUuidColumn = config.GetBoolean("akka.persistence.journal.sql.default.journal.use-writer-uuid-column"),
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString()
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_WithWriterUuidColumn)}");
    }

    [Fact]
    public async Task Configuration_WithCustomDatabaseMapping()
    {
        // Act - test custom database table mappings
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                databaseMapping: DatabaseMapping.SqlServer,
                schemaName: "custom_schema");
        });

        // Assert
        var snapshot = new
        {
            TableMapping = config.GetString("akka.persistence.journal.sql.table-mapping"),
            SchemaName = config.GetString("akka.persistence.journal.sql.sql-server.schema-name"),
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Snapshot = config.GetConfig("akka.persistence.snapshot-store.sql").ToString()
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_WithCustomDatabaseMapping)}");
    }

    [Fact]
    public async Task Configuration_WithDataOptions()
    {
        // Act - test DataOptions path
        var dataOptions = new DataOptions()
            .UseConnectionString(TestProviderName, ConnectionString);

        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                dataOptions: dataOptions,
                mode: PersistenceMode.Both,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("test-adapter",
                        new[] { typeof(TestEvent) }));
        });

        // Assert
        var snapshot = new
        {
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString(),
            Snapshot = config.GetConfig("akka.persistence.snapshot-store.sql").ToString(),
            EventAdapters = config.GetConfig("akka.persistence.journal.sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.sql.event-adapter-bindings")?.ToString() ?? "null"
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_WithDataOptions)}");
    }

    [Fact]
    public async Task Configuration_ComplexScenario_AllOptions()
    {
        // Act - test a complex scenario combining multiple options (similar to reported bug)
        var config = await BuildAndGetConfig(builder =>
        {
            builder.WithSqlPersistence(
                connectionString: ConnectionString,
                providerName: TestProviderName,
                mode: PersistenceMode.Both,
                tagStorageMode: TagMode.TagTable,
                useWriterUuidColumn: true,
                maxConcurrentQueries: 75,
                deleteCompatibilityMode: false,
                journalBuilder: journal => journal
                    .AddWriteEventAdapter<TestEventAdapter>("status-tagger",
                        new[] { typeof(TestEvent) }));
        });

        // Assert - comprehensive snapshot of all config sections
        var snapshot = new
        {
            // Journal config
            JournalTagWriteMode = config.GetString("akka.persistence.journal.sql.tag-write-mode"),
            JournalUseWriterUuid = config.GetBoolean("akka.persistence.journal.sql.default.journal.use-writer-uuid-column"),
            JournalDeleteCompat = config.GetBoolean("akka.persistence.journal.sql.delete-compatibility-mode"),

            // Query config
            QueryTagReadMode = config.GetString("akka.persistence.query.journal.sql.tag-read-mode"),
            QueryMaxConcurrent = config.GetInt("akka.persistence.query.journal.sql.max-concurrent-queries"),
            QueryWritePlugin = config.GetString("akka.persistence.query.journal.sql.write-plugin"),

            // Event adapters
            EventAdapters = config.GetConfig("akka.persistence.journal.sql.event-adapters")?.ToString() ?? "null",
            EventAdapterBindings = config.GetConfig("akka.persistence.journal.sql.event-adapter-bindings")?.ToString() ?? "null",

            // Full configs
            Journal = config.GetConfig("akka.persistence.journal.sql").ToString(),
            Query = config.GetConfig("akka.persistence.query.journal.sql").ToString(),
            Snapshot = config.GetConfig("akka.persistence.snapshot-store.sql").ToString()
        };

        await Verifier.Verify(snapshot)
            .UseDirectory("Snapshots")
            .UseMethodName($"{nameof(ConfigurationSnapshotSpec)}.{nameof(Configuration_ComplexScenario_AllOptions)}");
    }
}
